/* hewei 盘点日志*/
CREATE TABLE `TAKE_STOCK` (
  `TAKE_STOCK_ID` varchar(255) NOT NULL,
  `CREATE_TIME` varchar(255) DEFAULT NULL,
  `CREATE_YEARS` varchar(255) DEFAULT NULL,
  `OPERATOR` varchar(255) DEFAULT NULL,
  `IS_IMEI` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TAKE_STOCK_ID`)
);

CREATE TABLE `TAKE_STOCK_DETAIL` (
  `TAKE_STOCK_DETAIL_ID` varchar(255) NOT NULL,
  `TAKE_STOCK_ID` varchar(255) DEFAULT NULL,
  `IMEI_OR_EAN` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INVENTORY_QUANTITY` decimal(18,6) DEFAULT NULL,
  `DIF_QUANTITY` decimal(18,6) DEFAULT NULL,
  `REASON` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TAKE_STOCK_DETAIL_ID`)
);

CREATE TABLE `TAKE_STOCK_CATEGORY` (
  `TAKE_STOCK_ID` varchar(255) NOT NULL,
  `IMEI_OR_EAN` varchar(255) DEFAULT NULL,
  `QUANTITY` decimal(18,6) DEFAULT NULL
);

INSERT INTO `SECURITY_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `DYNAMIC_ACCESS`, `LAST_UPDATED_STAMP`, `LAST_UPDATED_TX_STAMP`, `CREATED_STAMP`, `CREATED_TX_STAMP`) 
VALUES ('WRHS_INV_CHECK', 'Permission to check inventory', NULL, '2017-08-30 00:00:00', '2017-08-30 00:00:00', '2017-08-30 00:00:00', '2017-08-30 00:00:00');