
/*麻烦先执行SQL再编译启动项目*/
CREATE TABLE `GOOD_IDENTIFICATION_MODIFY_LOG` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`GOOD_IDENTIFICATION_ID` VARCHAR(50) NULL,
	`MODIFY_TIME` TIMESTAMP NULL,
	`BEFORE_VALUE` VARCHAR(50) NULL,
	`AFTER_VALUE` VARCHAR(50) NULL,
	`OPERATOR` VARCHAR(50) NULL,
	`UPDATED_DATE` VARCHAR(50) NULL,
	`CREATED_USER` VARCHAR(50) NULL,
	`CREATED_DATE` VARCHAR(50) NULL,
	`UPDATED_USER` VARCHAR(50) NULL,
	
	`LAST_UPDATED_STAMP` DATETIME NULL,
	`LAST_UPDATED_TX_STAMP` DATETIME NULL,
	`CREATED_STAMP` DATETIME NULL,
	`CREATED_TX_STAMP` DATETIME NULL,
	INDEX `ID` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

