
/*麻烦先执行SQL再编译启动项目*/
CREATE TABLE `IMEI_WITH_PRODUCT_ID_LOG` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `IEMI` varchar(20) NOT NULL,
  `FROM_PRODUCT_ID` varchar(20) NOT NULL,
  `FROM_MODEL` varchar(255),
  `FROM_DESCRIPTION` varchar(255),
  `TO_PRODUCT_ID` varchar(20) NOT NULL,
  `TO_MODEL` varchar(255),
  `TO_DESCRIPTION` varchar(255),
  `OPERATOR` varchar(255) NOT NULL,
  `CREATE_TIME` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `SECURITY_PERMISSION` (`PERMISSION_ID`, `DESCRIPTION`, `DYNAMIC_ACCESS`, `LAST_UPDATED_STAMP`, `LAST_UPDATED_TX_STAMP`, `CREATED_STAMP`, `CREATED_TX_STAMP`) 
VALUES ('WRHS_INV_MPM', 'Permission to Modify Product Model', NULL, '2017-09-22 00:00:00', '2017-09-22 00:00:00', '2017-09-22 00:00:00', '2017-09-22 00:00:00');

/*麻烦先执行SQL再编译启动项目*/
CREATE TABLE `TRANSHIPMENT_SHIPPING_BILL_DETAIL` (
  `TRANSHIPMENT_SHIPPING_BILL_ID` varchar(20) NOT NULL,
  `IS_ACTIVE` char(255) DEFAULT NULL,
  `PRODUCT_ID` varchar(255) DEFAULT NULL,
  `IMEI` varchar(255) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER_lOGIN_ID` varchar(255) DEFAULT NULL,
  `LAST_UPDATE_USER_lOGIN_ID` varchar(255) DEFAULT NULL
 
);

ALTER TABLE `PRODUCT_STORE`
	ADD COLUMN `TIN_NO` VARCHAR(100) NULL DEFAULT NULL AFTER `ISSUPPORTACCOUNT`;
	

	
	
	
	

/*同步商品字段:用来判断商品是否已经同步*/
ALTER TABLE `PRODUCT`
	ADD COLUMN `B2R_PRODUCT_ID` VARCHAR(20) NOT NULL DEFAULT ''
	