/* hewei 20170726 */
ALTER TABLE PRODUCT_STORE ADD COLUMN COUNTRY_ID VARCHAR(100);

ALTER TABLE PRODUCT_STORE ADD COLUMN PROVINCE_ID VARCHAR(100);

ALTER TABLE PRODUCT_STORE ADD COLUMN CITY_ID VARCHAR(100);

ALTER TABLE PRODUCT_STORE ADD COLUMN AREA_ID VARCHAR(100);

/* yzl 20170727 */
delete  from JOB_SANDBOX where JOB_SANDBOX.JOB_NAME='regularRecord';