/* yzl 20170628  EAN码需求   对GOOD_IDENTIFICATION进行迁移做的表扩充*/

ALTER TABLE `GOOD_IDENTIFICATION`
	ADD COLUMN `ID` BIGINT NOT NULL AUTO_INCREMENT FIRST,
	ADD INDEX `ID` (`ID`),
ADD COLUMN `UPDATED_TIME` BIGINT(20) NULL AFTER `CREATED_TX_STAMP`,
ADD COLUMN `UPDATED_USER` VARCHAR(45) NULL AFTER `UPDATED_TIME`,
ADD COLUMN `CREATED_TIME` BIGINT(20) NULL AFTER `UPDATED_USER`,
ADD COLUMN `CREATED_USER` VARCHAR(45) NULL AFTER `CREATED_TIME`,
ADD COLUMN `UPDATED_DATE` VARCHAR(45) NULL AFTER `CREATED_USER`,
ADD COLUMN `CREATED_DATE` VARCHAR(45) NULL AFTER `UPDATED_DATE`;